// Particle effects 
class CfgCloudlets {
	class default; 
	class Blood;
	// blood effects -----------------------------------------------------------
	class BloodMist: Blood {
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal_02";
		particleFSNtieth = 8;
		particleFSIndex = 4;
		particleFSFrameCount = 1;
		particleFSLoop = 0;
		lifeTime = "0.4";
		size[] = {"(hit/50 + 0.5)","2*(hit/50 + 0.5)"};
		color[] = {{ 1,0,0,0.1 },{ 1,0,0,0.05 }};
		randomDirectionPeriod = 0.3;
		randomDirectionIntensity = 0.3;
		weight = 0.127;
	};
	class LAMBS_Blood : default {
		angleVar = 360; 
		animationName = "";
		animationSpeed[] = {0.1};
		beforeDestroyScript = "";
		blockAIVisibility = 0; 
		circleRadius = 0; 
		circleVelocity[] = {0,0,0};
		color[] = {
			{0.4,0.3,0.3,2},
			{0.4,0.3,0.3,2},
			{0.4,0.3,0.3,1.4},
			{0.4,0.3,0.3,0.8},
			{0.4,0.3,0.3,0.4},
			{0.4,0.3,0.3,0.05},
			{0.4,0.3,0.3,0.001}
		};
		colorVar[] = {0,0,0,0.2};
		destroyOnWaterSurface = 1;
		destroyOnWaterSurfaceOffset = -0.3;
		interval = 1;
		lifeTime = 0.1;
		lifeTimeVar = 0.02;
		moveVelocity[] = {0,0,0};
		MoveVelocityVar[] = {0,0,0};
		onTimerScript = "";
		particleFSFrameCount = 1;
		particleFSIndex = 13;
		particleFSLoop = 0;
		particleFSNtieth = 16;
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleType = "Billboard";
		positionVar[] = {0.01,0.01,0.01};
		randomDirectionIntensity = 0.55;
		randomDirectionIntensityVar = 0.15;
		randomDirectionPeriod = 0.5;
		randomDirectionPeriodVar = 0.3;
		rotationVelocity = 1;
		rotationVelocityVar = 8;
		rubbing = 0.05;
		size[] = {0.3,0.8};
		sizeVar = 0.8;
		timerPeriod = 1;
		volume = 0.1;
		weight = 0.1275;
	};
	// metal impact -------------------------------------------------------------------------
	class gokoFX_Starter_SparksBurstLOW : Default {
		interval = 0.001;
		color[] = { { 1, 0.8, 0.8, -500 }, { 1, 0.3, 0.1, -500 } };
		emissiveColor[] = { { 250, 180, 10, 0 }, { 0, 0, 0, 0 } };
		lifeTime = 0.015;
		lifeTimeVar = 0.5;
		weight = 1000;
		volume = 0.01;
		rubbing = 0.15;
		size[] = { 0.1, 0.035, 0 };
		sizeVar = 0.4;
		moveVelocity[] = {"surfNormalX * inSpeed / 250 * 1.33","surfNormalY * inSpeed / 250 * 1.33","surfNormalZ * inSpeed / 250"};
		moveVelocityVar[] = { 1, 1, 1};
		bounceOnSurface = 0.1;
		bounceOnSurfaceVar = 0.2;
		circleRadius = 0;
		circleVelocity[] = { 0, 0, 0 };
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 360;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		rotationVelocity = 1;
		colorCoef[] = { 1, 1, 1, 1 };
		animationSpeed[] = { 1000 };
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		blockAIVisibility = 0;
		position[] = { 0, 0, 0 };
		positionVar[] = { 0.01, 0.01, 0.01 };
		rotationVelocityVar = 0;
		colorVar[] = { 0.05, 0.05, 0.05, 5 };
		randomDirectionPeriodVar = 0.09;
		randomDirectionIntensityVar = 2.3;
	};
	class gokoFX_Starter_SparksBurstMed : Default {
		interval = 0.001;
		color[] = { { 1, 0.3, 0.1, -500 }, { 1, 0.3, 0.1, -500 } };
		emissiveColor[] = { { 235, 235, 250, 0 }, { 0, 0, 0, 0 } };
		lifeTime = 0.015;
		lifeTimeVar = 0.5;
		weight = 1000;
		volume = 0.01;
		rubbing = 0.15;
		size[] = { 0.1, 0.035, 0 };
		sizeVar = 0.4;
		moveVelocity[] = {"surfNormalX * inSpeed / 250 * 1.33","surfNormalY * inSpeed / 250 * 1.33","surfNormalZ * inSpeed / 250"};
		moveVelocityVar[] = {1,1,1};
		bounceOnSurface = 0.1;
		bounceOnSurfaceVar = 0.2;
		circleRadius = 0;
		circleVelocity[] = { 0, 0, 0 };
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 360;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		rotationVelocity = 1;
		colorCoef[] = { 1, 1, 1, 1 };
		animationSpeed[] = { 1000 };
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		blockAIVisibility = 0;
		position[] = { 0, 0, 0 };
		positionVar[] = { 0.01, 0.01, 0.01 };
		rotationVelocityVar = 0;
		colorVar[] = { 0.05, 0.05, 0.05, 5 };
		randomDirectionPeriodVar = 0.09;
		randomDirectionIntensityVar = 2.3;
	};
	class gokoFX_Starter_SparksBurst : Default {
		interval = 0.001;
		color[] = { { 1, 0.3, 0.1, -500 }, { 1, 0.3, 0.1, -500 } };
		emissiveColor[] = { { 250, 80, 25, 0 }, { 0, 0, 0, 0 } };
		lifeTime = 0.015;
		lifeTimeVar = 1;
		weight = 1000;
		volume = 0.01;
		rubbing = 0.15;
		size[] = { 0.075, 0.015, 0 };
		sizeVar = 0.5;
		moveVelocity[] = {"surfNormalX * inSpeed / 250 * 0.66","surfNormalY * inSpeed / 250 * 0.66","surfNormalZ * inSpeed / 250 * 0.66"};
		moveVelocityVar[] = { 0.1, 0.1, 0.1};
		bounceOnSurface = 0.05;
		bounceOnSurfaceVar = 0.1;
		circleRadius = 0;
		circleVelocity[] = { 0, 0, 0 };
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 360;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		rotationVelocity = 1;
		colorCoef[] = { 1, 1, 1, 1 };
		animationSpeed[] = { 1000 };
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		blockAIVisibility = 0;
		position[] = { 0, 0, 0 };
		positionVar[] = { 0.01, 0.01, 0.01 };
		rotationVelocityVar = 0;
		colorVar[] = { 0.05, 0.05, 0.05, 5 };
		randomDirectionPeriodVar = 0.1;
		randomDirectionIntensityVar = 0.2;
	};
	class gokoFX_Starter_SparksBurst1 : Default {
		interval = 0.001;
		color[] = { { 1, 0.3, 0.1, -500 }, { 1, 0.3, 0.1, -500 } };
		emissiveColor[] = { { 250, 225, 160, 0 }, { 0, 0, 0, 0 } };
		lifeTime = 0.015;
		lifeTimeVar = 1;
		weight = 1000;
		volume = 0.01;
		rubbing = 0.15;
		size[] = { 0.075, 0.015, 0 };
		sizeVar = 0.5;
		moveVelocity[] = {"surfNormalX * inSpeed / 250 * 0.66","surfNormalY * inSpeed / 250 * 0.66","surfNormalZ * inSpeed / 250 * 0.66"};
		moveVelocityVar[] = { 0.1, 0.1, 0.1};
		bounceOnSurface = 0.2;
		bounceOnSurfaceVar = 0.3;
		circleRadius = 0;
		circleVelocity[] = { 0, 0, 0 };
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 360;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		rotationVelocity = 1;
		colorCoef[] = { 1, 1, 1, 1 };
		animationSpeed[] = { 1000 };
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0.05;
		randomDirectionIntensity = 0.1;
		onTimerScript = "";
		beforeDestroyScript = "";
		blockAIVisibility = 0;
		position[] = { 0, 0, 0 };
		positionVar[] = { 0.01, 0.01, 0.01 };
		rotationVelocityVar = 0;
		colorVar[] = { 0.05, 0.05, 0.05, 5 };
		randomDirectionPeriodVar = 0.1;
		randomDirectionIntensityVar = 0.2;
	};
	class gokoFX_Starter_SparksBurst2 : Default {
		interval = 0.001;
		color[] = { { 1, 1, 0.9, -500 }, { 1, 0.3, 0.1, -500 } };
		emissiveColor[] = { { 252, 255, 128, 0 }, { 0, 0, 0, 0 } };
		lifeTime = 0.015;
		lifeTimeVar = 1;
		weight = 1000;
		volume = 0.01;
		rubbing = 0.15;
		size[] = { 0.175, 0.015, 0 };
		sizeVar = 0.5;
		moveVelocity[] = {"surfNormalX * inSpeed / 250","surfNormalY * inSpeed / 250","surfNormalZ * inSpeed / 250"};
		moveVelocityVar[] = {"surfNormalX * inSpeed / 250","surfNormalY * inSpeed / 250","surfNormalZ * inSpeed / 250"};
		bounceOnSurface = 0.2;
		bounceOnSurfaceVar = 0.1;
		circleRadius = 0;
		circleVelocity[] = { 0, 0, 0 };
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 360;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		rotationVelocity = 1;
		colorCoef[] = { 1, 1, 1, 1 };
		animationSpeed[] = { 1000 };
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0.5;
		randomDirectionIntensity = 1;
		onTimerScript = "";
		beforeDestroyScript = "";
		blockAIVisibility = 0;
		position[] = { 0, 0, 0 };
		positionVar[] = { 0.01, 0.01, 0.01 };
		rotationVelocityVar = 1;
		colorVar[] = { 0.05, 0.05, 0.05, 5 };
		randomDirectionPeriodVar = 0.5;
		randomDirectionIntensityVar = 2;
	};
	class gokoFX_Starter_SparksStream : gokoFX_Starter_SparksBurst {
		interval = 0.001;
		lifeTime = 0.15;
		lifeTimeVar = 5;
		moveVelocity[] = { 1, 5, 1 };
		moveVelocityVar[] = {"surfNormalX * inSpeed / 250 * 0.66","surfNormalY * inSpeed / 250 * 0.66","surfNormalZ * inSpeed / 250 * 0.66"};
		bounceOnSurface = 0.1;
		bounceOnSurfaceVar = 0.1;
	};
	class gokoFX_Starter_SparksOmni : gokoFX_Starter_SparksBurst2 {
		interval = 0.008;
		lifeTime = 0.05;
		lifeTimeVar = 1;
		moveVelocity[] = {"surfNormalX * inSpeed / 200","surfNormalY * inSpeed / 200","surfNormalZ * inSpeed / 200"};
		moveVelocityVar[] = {"surfNormalX * inSpeed / 200","surfNormalY * inSpeed / 200","surfNormalZ * inSpeed / 200"};
		bounceOnSurface = 0.1;
		bounceOnSurfaceVar = 0.1;
	};
	class gokoFX_Starter_SparksOmniSparkle : gokoFX_Starter_SparksOmni {
		interval = 0.5;
		size[] = { 0.15, 0.05, 0 };
		moveVelocity[] = { 1, 1, 1 };
		moveVelocityVar[] = { 0.1, -1, 0.1 };
		postEffects = "gokoFX_SparksSparkleEffect";
	};
	class gokoFX_Starter_SparksOmniSparklings : gokoFX_Starter_SparksBurst1 {
		interval = 0.0003;
		lifeTime = 0.003;
		lifeTimeVar = 1;
		moveVelocity[] = { 0.7, 0.7, 0.1 };
		moveVelocityVar[] = { 2, 2, 0.3};
	};
	class gokoFX_Starter_SparksDrop2 : gokoFX_Starter_SparksBurst {
		interval = 100;
		lifeTime = 0.5;
		lifeTimeVar = 1;
		moveVelocity[] = { -0.1, -1, -0.1 };
		moveVelocityVar[] = { 0.2, 2, 0.2 };
		bounceOnSurface = 0;
		bounceOnSurfaceVar = 0;
		postEffects = "gokoFX_SparksSparkleEffect";
	};
	class gokoFX_Starter_SparksDrop : gokoFX_Starter_SparksBurst {
		interval = 0.020;
		lifeTime = 0.05;
		lifeTimeVar = 3;
		moveVelocity[] = { 0.3, -2, 0.3 };
		moveVelocityVar[] = { 0.3, 0, 0.3 };
		bounceOnSurface = 0.1;
		bounceOnSurfaceVar = 0.2;
	};
	class gokoFX_Starter_SparksDropLightFire : gokoFX_Starter_SparksBurst {
		interval = 0.3;
		lifeTime = 0.1;
		lifeTimeVar = 0.2;
		size[] = { 0.25, 0.10, 0 };
		sizeVar = 0.5;
		moveVelocity[] = { 1, 0, 1 };
		moveVelocityVar[] = { 1, 0, 1 };
		bounceOnSurface = -1;
		bounceOnSurfaceVar = 0.0;
		particleEffects = "gokoFX_SparksLightFireEffect";
	};
	// concrete impact --------------------------------------
	class ImpactConcrete : Default {
		animationName = "";
		animationSpeed[] = {1000}; 
		beforeDestroyScript = ""; 
		bounceOnSurface = 0; 
		bounceOnSurfaceVar = 0;
		circleRadius = 0;
		circleVelocity[] = {0,0,0};
		color[] = {{0.5,0.5,1,1}};
		colorVar[] = {0,0,0,0};
		destroyOnWaterSurface = 1;
		destroyOnWaterSurfaceOffset = -0.2;
		interval = 0.025;
		lifeTime = 9;
		lifeTimeVar = 5;
		//moveVelocity[] = {"(surfNormalX / 2) * inSpeed / 150 * 0.66","(surfNormalY / 2) * inSpeed / 150 * 0.66","(surfNormalZ / 2) * inSpeed / 150 * 0.66"};
		moveVelocity[] = {"surfNormalX * inSpeed / 250","surfNormalY * inSpeed / 250","surfNormalZ * inSpeed / 250 * 0.66"};
		moveVelocityVar[] = {1,1,1};
		onTimerScript = "";
		particleShape = "\A3\data_f\ParticleEffects\pstone\pstone.p3d";
		particleType = "spaceobject";
		/*
		particleFSFrameCount = 9;
		particleFSIndex = 12;
		particleFSLoop = 0;
		particleFSNtieth = 16;
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleType = "Billboard";
		*/
		positionVar[] = {0.05,0.05,0.05};
		randomDirectionIntensity = 0;
		randomDirectionIntensityVar = 0;
		randomDirectionPeriod = 0;
		randomDirectionPeriodVar = 0;
		rotationVelocity = 1;
		rotationVelocityVar = 1;
		rubbing = 0.03;
		size[] = {0.12};
		sizeVar = 0.3; // 0.4
		timerPeriod = 0.1;
		volume = 1;
		weight = 5;
	}; 
	class ImpactSandSmoke2; 
	class LAMBS_ImpactSandSmoke2 : ImpactSandSmoke2 {
		moveVelocity[] = {"surfNormalX * inSpeed / 250","surfNormalY * inSpeed / 250","surfNormalZ * inSpeed / 250 * 0.66"};
		moveVelocityVar[] = {1,1,2};
		size[] = {0.3,0.9};
		sizeVar = 0.5;
		volume = 0.2;
	};
	class LAMBS_ImpactConcrete : ImpactSandSmoke2 {
		moveVelocity[] = {"surfNormalX * inSpeed / 250","surfNormalY * inSpeed / 250","surfNormalZ * inSpeed / 250 * 0.1"};
		moveVelocityVar[] = {1,1,3};
		size[] = {0.2,0.3};
		sizeVar = 0.7;
		color[] = {{0.6,0.6,0.6,0.6},{1,1,1,0}};
		particleFSFrameCount = 5;
		particleFSIndex = 14;
		particleFSLoop = 0;
		particleFSNtieth = 16;		
		animationSpeed[] = {1};
		weight = 3.5;
	};
};	

class gokoFX_SparksSparkleEffect {
	class gokoFX_Starter_SparksOmniSparklings {
		simulation = "particles";
		type = "gokoFX_Starter_SparksOmniSparklings";
		position[] = {0,0,0};
		intensity = 1;
		interval = 1;
		lifeTime = 0.03;

	};
};
